[colors]
ansi = [
	 '#232627', # black
	 '#cc2263', # red
	 '#40da76', # green
	 '#da7340', # yellow
	 '#2080bb', # blue
	 '#a740da', # purple
	 '#61c583', # cyan
	 '#afb3bd', # white
]
brights = [
	 '#767676', # black
	 '#e2266e', # red
	 '#4bff8a', # green
	 '#dac040', # yellow
	 '#40a5da', # blue
	 '#c14afd', # purple
	 '#72e69a', # cyan
	 '#ecf2ff', # white
]

background = '#21242b'
foreground = '#ffffff'

cursor_bg = '#ffffff'
cursor_border  = '#000000'
cursor_fg = '#21242b'

selection_bg = '#40a5da'
selection_fg = '#21242b'

[colors.indexed]

[metadata]
name = 'OM-Colors'
